export type DomainErrorCode =
  | "INVALID_PLAYER_COUNT"
  | "INVALID_POSITION"
  | "OUT_OF_BOUNDS"
  | "ROUND_NOT_READY"
  | "MATCH_ALREADY_COMPLETED"
  | "NOT_ACTIVE_PLAYER"
  | "PRIORITY_ALREADY_SUBMITTED"
  | "PRIORITY_CARD_NOT_AVAILABLE"
  | "AUCTION_BID_ALREADY_SUBMITTED"
  | "INVALID_AUCTION_BID"
  | "SPECIAL_CARD_NOT_OWNED"
  | "INVALID_SPECIAL_CARD_TARGET"
  | "MANDATORY_STEP_REQUIRED"
  | "SECONDARY_ACTION_NOT_AVAILABLE"
  | "PLAYER_ELIMINATED"
  | "PLAYER_ALREADY_CARRYING_TREASURE"
  | "PLAYER_NOT_CARRYING_TREASURE"
  | "ACTION_BLOCKED_BY_TREASURE"
  | "TREASURE_NOT_FOUND"
  | "TREASURE_ALREADY_OPENED"
  | "TREASURE_ALREADY_CARRIED"
  | "TREASURE_NOT_AT_PLAYER_POSITION"
  | "TREASURE_NOT_AT_START"
  | "TREASURE_PLACEMENT_NOT_ALLOWED"
  | "ROUND_ALREADY_COMPLETED"
  | "INVALID_TILE_SOURCE"
  | "INVALID_THROW_TARGET"
  | "TILE_NOT_THROWABLE"
  | "ROTATION_BLOCKED_BY_PLAYER"
  | "INVALID_ROTATION_SELECTION"
  | "MOVEMENT_BLOCKED_BY_FENCE";

export class DomainError extends Error {
  public readonly code: DomainErrorCode;

  public constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.code = code;
  }
}
